### ISSUE TITLE
 width = max([len(line) for c in self._content for line in c]) No content in figure

### ISSUE THREAD

**Issue by hudengjunai** [nschloe/termplotlib#43]
```python
import termplotlib as tpl
import numpy

x = numpy.linspace(0, 2 * numpy.pi, 10)
y = numpy.sin(x)

fig = tpl.figure()
fig.plot(x, y, label="data", width=50, height=15)
fig.show()
```

after run this piece of code ,there are error ,

```
if self._width is None:
---> 33             width = max([len(line) for c in self._content for line in c])
     34             width += padding_lr
     35         else:
```
did you come up with this problem?

**Comment by nschloe** [comment]
Cannot produce:
```
    1 +---------------------------------------+
  0.8 |    **     **                          |
  0.6 |   *         **           data ******* |
  0.4 | **                                    |
  0.2 |*              **                      |
    0 |                 **                    |
      |                                   *   |
 -0.2 |                   **            **    |
 -0.4 |                     **         *      |
 -0.6 |                              **       |
 -0.8 |                       **** **         |
   -1 +---------------------------------------+
      0     1    2     3     4     5    6     7
```

**Comment by rockt** [comment]
I have the same issue
```                                                                                                                                                                                                                                                                                            
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import termplotlib as tpl
>>> import numpy
>>>
>>> x = numpy.linspace(0, 2 * numpy.pi, 10)
>>> y = numpy.sin(x)
>>>
>>> fig = tpl.figure()
>>> fig.plot(x, y, label="data", width=50, height=15)
>>> fig.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../python3.7/site-packages/termplotlib/figure.py", line 24, in show
    print(self.get_string())
  File "/Users/.../python3.7/site-packages/termplotlib/figure.py", line 33, in get_string
    width = max([len(line) for c in self._content for line in c])
ValueError: max() arg is an empty sequence
```

**Comment by nschloe** [comment]
Please make your code copy-pastable.

**Comment by rockt** [comment]
```python
import termplotlib as tpl
import numpy

x = numpy.linspace(0, 2 * numpy.pi, 10)
y = numpy.sin(x)

fig = tpl.figure()
fig.plot(x, y, label="data", width=50, height=15)
fig.show()
```

**Comment by nschloe** [comment]
Cannot reproduce:
```
    1 +---------------------------------------+
  0.8 |    **     **                          |
  0.6 |   *         **           data ******* |
  0.4 | **                                    |
  0.2 |*              **                      |
    0 |                 **                    |
      |                                   *   |
 -0.2 |                   **            **    |
 -0.4 |                     **         *      |
 -0.6 |                              **       |
 -0.8 |                       **** **         |
   -1 +---------------------------------------+
      0     1    2     3     4     5    6     7
```

**Comment by nschloe** [comment]
@rockt This is literally the _same_ thing that OP posted. :-1:

**Comment by rockt** [comment]
Indeed, even better: it's the example from the project's README. The reason I commented on this issue is for you to see additional information on the error that both @hudengjunai and I get.

**Comment by nschloe** [comment]
[Like I said](https://github.com/nschloe/termplotlib/issues/43#issuecomment-620436672): I cannot reproduce it, so I have no way of fixing it. PRs welcome!

**Comment by Farbdrucker** [comment]
having the same issue with `termplotlib==0.2.4` with provided example

**Comment by t-springborn** [comment]
The sourcecode in the github repository is not identical to the sourcecode installed by pip.
In figure.py line 31-35 are:
`if self._width is None:
            line_lengths = [len(line) for c in self._content for line in c]
            width = max(line_lengths) if line_lengths else 0
            width += padding_lr`
in the pip install it is:
`if self._width is None:
            width = max([len(line) for c in self._content for line in c])
            width += padding_lr`
This removes the check for empty content.

Fixing this still doesn't make it create a plot, but it removes the error message. I suspect there is another discrepancy somewhere.
@nschloe I assume this code discrepancy is why you couldn't reproduce the error.

**Comment by nschloe** [comment]
I pushed a new version (0.3.3) to pypi, and since I cannot reproduce the issue, I'll assume it's fixed somehow. Please reopen if this doesn't work for you.
