### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by mscampos92** [nschloe/termplotlib#45]
Dear nschloe, your lib sounds nice!
I got a different error in that code..
Any idea?
```
Traceback (most recent call last):
  File ".\app.py", line 51, in <module>
    fig.plot(x, y)
  File "mypath\env\lib\site-packages\termplotlib\figure.py", line 64, in plot
    self._content.append(plot(*args, **kwargs))
  File "mypath\env\lib\site-packages\termplotlib\plot.py", line 22, in plot
    stderr=subprocess.PIPE,
  File "mypath\appdata\local\programs\python\python37\Lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "mypath\appdata\local\programs\python\python37\Lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by nschloe** [comment]
Looks like you don't have gnuplot installed.

**Comment by mscampos92** [comment]
Ok, I installed, restarted my computer and the error keeps.
I'm using vs code, can I use that integrated terminal to run that python script?

**Comment by nschloe** [comment]
No idea. Still sound like an installation issue, perhaps termplotlib cannot find gnuplot.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen if the issue persists.
